version: "3.2"
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
    image: mathfm/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
    image: mathfm/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  bootcamp-user-api:
    build:
      context: ../fernando-santos-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: mathfm/app-user-api:latest
    ports:
      - 8082:8082
    container_name: app-user-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
