spring:
  application:
    name: bootcamp Sysmap 2024 - Fernando Santos
    main:
      allow-bean-definition-overriding: true
      allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /api


